### PR TITLE
Use new compiler in LSP

### LINKED ISSUE #615: Edition 2024 support
### Feature

When I try and use Edition 2024 in VS Code I get errors 'edition "2024" not yet fully supported; latest supported edition "2023"'. This is using v0.8.16 of the extension, and in the "Output" window in VS Code I'm seeing logs:

```
INFO	starting LSP server	{"buf_version":"1.68.1"}
INFO	client attached	{"buf_version":"1.68.1","client_name":"Visual Studio Code","client_version":"1.115.0"}
INFO	file updated	{"buf_version":"1.68.1","uri":"/home/user/.../file.proto","old_version":-1,"new_version":1}
INFO	parsing IR for file	{"buf_version":"1.68.1","uri":"file:///home/user/.../file.proto","version":1}
WARN	error building image	{"buf_version":"1.68.1","path":".../file.proto","error":"parse failed: invalid proto source"}
```

### PR DESCRIPTION
**Pull request by stefanvanburen**
Fixes bufbuild/vscode-buf#615.

### CODE REVIEW

File: private/bufpkg/bufimage/build_image.go [hunk 1]
```diff
@@ -176,44 +178,149 @@ func compileImage(
...
+
+	// Use context.WithoutCancel to prevent external context cancellation from
+	// triggering an early return in incremental.Resolve while background goroutines
+	// are still running. A bug in protocompile causes those goroutines to access
+	// the (now-nil) named return slice after early return, causing a nil-index panic.
+	// The queries are pure in-memory work and complete quickly; shielding them from
+	// cancellation does not cause meaningful delays. We check ctx.Err() after Run
+	// completes to propagate the original cancellation to the caller.
+	results, diagnostics, err := incremental.Run(
+		context.WithoutCancel(ctx),
```
Comment (stefanvanburen) [inline private/bufpkg/bufimage/build_image.go]: can nix this workaround with https://github.com/bufbuild/protocompile/pull/709

**Review by emcfarlane — APPROVED** [review]

File: private/bufpkg/bufimage/build_image.go (hunk 1 above)
Comment (emcfarlane) [reply private/bufpkg/bufimage/build_image.go]: Lets fix this issue before merging.

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 ## [Unreleased]
 
+- Fix LSP incorrectly reporting "edition '2024' not yet fully supported" errors for proto files using Edition 2024 by migrating the LSP image builder to the new compiler, which already supports Edition 2024.
```
Comment (emcfarlane) [inline CHANGELOG.md]:
```suggestion
- Fix LSP incorrectly reporting "edition '2024' not yet fully supported" errors.
```
Probably fine to simply to just the error, maybe could say on checks?

**Review by emcfarlane — APPROVED** [review]
