### PR TITLE
Fix formatting of C-style block comments that use prefix symbols on each line

### LINKED ISSUE #1839: buf format: comment whitespace is still a little wonky
Hi,

We've noticed that when upgrading buf from 1.8 to 1.9 (as documented in https://github.com/bufbuild/buf/issues/1612), whitespace behavior in multiline comment blocks changed.

It was addressed in 1.10 (per https://github.com/bufbuild/buf/pull/1615) but it looks like there are still persistent issues with multiline comment formatting.

For example, on 1.14, we're seeing this diff introduced in our protobuf:

```diff
 /*
- * Information that is associated with a vulnerability network that we need to be able to store,
- * filter, search, and then obtain for use.
- */
+   * Information that is associated with a vulnerability network that we need to be able to store,
+   * filter, search, and then obtain for use.
+*/
 message Asset {
   /*
-   * Meta information about the asset that can be used to identify and categorize the asset.
-   */
+     * Meta information about the asset that can be used to identify and categorize the asset.
+  */
   message Info {
     string id = 1;
     string name = 2;
     optional string description = 3;
     bool stable = 4;
     optional string context = 5;
     string type = 6;
   }
```

which really just looks....wonky. Here's a side-by-side comparison.

before (buf 1.7):
```protobuf
/*
 * Information that is associated with a vulnerability network that we need to be able to store,
 * filter, search, and then obtain for use.
 */
message Asset {
  /*
   * Meta information about the asset that can be used to identify and categorize the asset.
   */
  message Info {
    string id = 1;
    string name = 2;
    optional string description = 3;
    bool stable = 4;
    optional string context = 5;
    string type = 6;
  }
```

after (buf 1.8):
```protobuf
/*
   * Information that is associated with a vulnerability network that we need to be able to store,
   * filter, search, and then obtain for use.
*/
message Asset {
  /*
     * Meta information about the asset that can be used to identify and categorize the asset.
  */
  message Info {
    string id = 1;
    string name = 2;
    optional string description = 3;
    bool stable = 4;
    optional string context = 5;
    string type = 6;
  }
```

### PR DESCRIPTION
**Pull request by jhump**
Fixes #1839

### CODE REVIEW

File: private/buf/bufformat/formatter.go [hunk 1]
```diff
@@ -2048,9 +2067,45 @@ func (f *formatter) writeComment(comment string) {
...
+
+			// But if there IS a prefix, "|" for example, we'll left-align
+			// the prefix symbol under the asterisk of the comment start
+			// like this:
+
+			/*
+			 | This comment has a prefix before each line.
+			 | Usually the prefix is asterisk, but it's a
+			 | pipe in this example.
+			*/
```
Comment (jhump) [inline private/buf/bufformat/formatter.go:2086]: I had considered lining up the asterisk of the trailing `*/` so it is left-aligned underneath the other symbols. _However_, I couldn't even put an example like that in here because `gofmt` would unindent the `*/` by one space.

So this alignment of the `*/` terminator is inspired by `gofmt`. Its rules appear to be that the `*/` is exactly aligned with the `/*` _unless_ each comment line starts with an asterisk, in which case it is aligned exactly one space to the right of the `/*` so that the asterisks all line up.

**Review by pkwarren — APPROVED** [review]

**Review by pkwarren — APPROVED** [review]
