### PR TITLE
Handle files that have not completed lowering in LSP

### LINKED ISSUE #4434: Buf LSP panics in DocumentSymbol via ir.Type.Deprecated on devel build
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with `github.com/bufbuild/buf` or we will automatically close your issue, see the instructions above!)

Private repository. I can try to reduce this to a minimal public repro if needed, but I wanted to report the exact crash signature first because it looks like a new variant of earlier Buf LSP panics around deprecated-symbol handling.

### Commands

```shell
buf lsp serve --timeout=0 --log-format=json
```

### Output

```text
INFO	starting LSP server	{"buf_version":"(devel)"}
INFO	client attached	{"buf_version":"(devel)","client_name":"Visual Studio Code","client_version":"1.114.0"}
INFO	file updated	{"buf_version":"(devel)","uri":"/Users/mklein/Source/internal-core/proto-internal/src/bitdrift/internal_api/unary/explorations/v1/workflow.proto","old_version":-1,"new_version":1}
INFO	parsing IR for file	{"buf_version":"(devel)","uri":"file:///Users/mklein/Source/internal-core/proto-internal/src/bitdrift/internal_api/unary/explorations/v1/workflow.proto","version":1}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103e3f40c]

goroutine 31 [running]:
github.com/bufbuild/protocompile/experimental/ir.MessageValue.Field({{{0x0?}, 0x0?, 0x44d6345?}}, {{{0x0?}, 0x0?, 0x0?}})
  github.com/bufbuild/protocompile@v0.14.2-0.20260306221011-519528254156/experimental/ir/ir_value.go:799 +0xcc
github.com/bufbuild/protocompile/experimental/ir.Type.Deprecated({{{0x5444046a38c8?}, 0x544404bc0008?, 0x361?}})
  github.com/bufbuild/protocompile@v0.14.2-0.20260306221011-519528254156/experimental/ir/ir_type.go:596 +0xa4
github.com/bufbuild/protocompile/experimental/ir.Symbol.Deprecated({{{0x5444046a38c8?}, 0x544406baa60c?, 0x4140518?}})
  github.com/bufbuild/protocompile@v0.14.2-0.20260306221011-519528254156/experimental/ir/ir_symbol.go:140 +0x70
github.com/bufbuild/buf/private/buf/buflsp.(*symbol).GetSymbolInformation(0x544405f85e60)
  github.com/bufbuild/buf/private/buf/buflsp/symbol.go:359 +0x14c
github.com/bufbuild/buf/private/buf/buflsp.(*server).DocumentSymbol.(*file).GetSymbols.func1(...)
  github.com/bufbuild/buf/private/buf/buflsp/file.go:1206
github.com/bufbuild/buf/private/buf/buflsp.(*server).DocumentSymbol(0x544403a68cf0?, {0x105686840?, 0x5444058dc760?}, 0x103de50c8?)
  github.com/bufbuild/buf/private/buf/buflsp/server.go:500 +0x168
go.lsp.dev/protocol.serverDispatch({0x105c7dfb0, 0x544404066230}, {0x105ce53b8, 0x54440441aa68}, 0x54440496bea8, {0x105c7fc38, 0x5444040514c0})
  go.lsp.dev/protocol@v0.12.0/server.go:386 +0x6e94
github.com/bufbuild/buf/private/buf/buflsp.(*lsp).newHandler.ServerHandler.func2({0x105c7dfb0, 0x544404066230}, 0x54440496bea8, {0x105c7fc38, 0x5444040514c0})
  go.lsp.dev/protocol@v0.12.0/server.go:36 +0x68
github.com/bufbuild/buf/private/buf/buflsp.(*lsp).newHandler.func1({0x105c7dfb0, 0x544404066230}, 0x54440441ac90, {0x105c7fc38, 0x5444040514c0})
  github.com/bufbuild/buf/private/buf/buflsp/buflsp.go:190 +0x290
github.com/bufbuild/buf/private/buf/buflsp.(*lsp).newHandler.AsyncHandler.func3.2()
  go.lsp.dev/jsonrpc2@v0.10.0/handler.go:114 +0x6c
created by github.com/bufbuild/buf/private/buf/buflsp.(*lsp).newHandler.AsyncHandler.func3 in goroutine 27
  go.lsp.dev/jsonrpc2@v0.10.0/handler.go:112 +0x140
[Error - 9:01:01 AM] The Buf Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:01:01 AM] Server process exited with code 2.
```

### Expected Output

The LSP should not panic when serving `textDocument/documentSymbol` for this file.

### Anything else?

Environment:
- Buf version: `(devel)`
- VS Code: `1.114.0`
- OS: macOS
- protocompile in stack: `v0.14.2-0.20260306221011-519528254156`

This looks related to earlier Buf LSP crash reports, but I did not find an exact duplicate for this stack:
- #4192
- #4218
- #4234

What seems distinct here is that the panic goes through:
- `ir.MessageValue.Field`
- `ir.Type.Deprecated`
- `ir.Symbol.Deprecated`
- `buflsp.(*symbol).GetSymbolInformation`
- `DocumentSymbol`

So this looks like another nil-deref in deprecated-symbol handling, but for `Type.Deprecated` on the current protocompile snapshot rather than the previously reported cases.

I have not yet reduced this to a minimal public repro. If it helps triage, I can try to isolate the specific proto shape or import graph that triggers it.

### PR DESCRIPTION
**Pull request by doriable**
This implements more graceful behaviour in the LSP for when
a file is unable to go through the full lowering process, and therefore
cannot/does not have fully resolved symbols for LSP functionality, and
attempts to return the most helpful possible diagnostic to the user to
communicate this.

Fixes #4434

### CODE REVIEW

File: private/buf/buflsp/file.go [hunk 1]
```diff
@@ -338,11 +350,26 @@ func (f *file) queryFileKeys() []any {
...
 
+	// The file has not completed lowering, so we cannot continue with symbol indexing here.
+	// To help the user better understand/diagnose this problem, we surface an additional
+	// diagnostic here.
+	if !f.ir.Lowered() {
+		f.diagnostics = append(f.diagnostics, protocol.Diagnostic{
+			Source:   serverName,
+			Severity: protocol.DiagnosticSeverityError,
+			Message: fmt.Sprintf(`the symbols for this file have not been fully resolved due to an invalid version of descriptor.proto located at: %q.
+this is likely due to a vendored descriptor.proto.`,
```
Comment (stefanvanburen) [inline private/buf/buflsp/file.go]: nit: I think the diagnostics tend to be sentence-cased?
```suggestion
			Message: fmt.Sprintf(`The symbols for this file have not been fully resolved due to an invalid version of descriptor.proto located at: %q.
This is likely due to a vendored descriptor.proto.`,
```

File: private/buf/buflsp/diagnostic.go [hunk 2]
```diff
@@ -41,10 +43,16 @@ var reportLevelToDiagnosticSeverity = map[report.Level]protocol.DiagnosticSeveri
 func reportDiagnosticToProtocolDiagnostic(
 	reportDiagnostic report.Diagnostic,
 ) protocol.Diagnostic {
+	message := reportDiagnostic.Message()
+	if reportDiagnostic.Level() == report.ICE {
+		// Include notes for ICE
+		notes := append([]string{message}, reportDiagnostic.Notes()...)
+		message = strings.Join(notes, " ")
+	}
```
Comment (stefanvanburen) [inline private/buf/buflsp/diagnostic.go:51]: neat; separately, feels like we ought to integrate `.Notes()` / `.Help()` / `.Debug()` somehow when they're available, and not just conditionally?

**Review by stefanvanburen — COMMENTED** [review]
👍, just a quick drive-by

File: private/buf/buflsp/diagnostic.go (hunk 2 above)
Comment (doriable) [reply private/buf/buflsp/diagnostic.go:51]: Yeah -- I think the follow-up once the compiler is fully ported, and the `Help`/`Debug` in particular are reaching much stabler state than when the LSP was first launched, we should turn them into code actions. So there's definitely some follow-up improvements to do here.

**Review by stefanvanburen — APPROVED** [review]

**Review by emcfarlane — APPROVED** [review]
