### PR TITLE
Fix issue where netrc files larger than 4096 bytes would get corrupted on update

### LINKED ISSUE #611: buf registry login corrupts large netrc files
A customer reported that their `.netrc` file ended up slightly scrambled after invoking `buf login` when there was a lot of existing data in the file. This was their `.netrc` before `buf login`:

```
machine asia-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-east1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-east2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-northeast1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-northeast2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-northeast3-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-south1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-south2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-southeast1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine asia-southeast2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine australia-southeast1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine australia-southeast2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-central2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-north1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west3-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west4-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west5-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine europe-west6-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine northamerica-northeast1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine northamerica-northeast2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine southamerica-east1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-central1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-east1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-east4-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-west1-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-west2-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-west3-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
machine us-west4-python.pkg.dev login oauth2accesstoken password somepassword............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

After running `buf login`, it appears part of some of the lines were truncated. More investigation is necessary.

### PR DESCRIPTION
**Pull request by bufdev**
Fixes #611.

There is some issue with `bufio.Scanner` usage in github.com/bgentry/go-netrc where if the file sizse is greater than 4096 bytes, the scanning has a silent error. This is likely related to the `startBufSize` at https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/bufio/scan.go;l=83, and potentially even a bug in golang/go itself.

This PR has a hacky mitigation, by calling `scanner.Buffer` with a buffer of size `max(4096, len(file))` and a max token size of either 1MB, or `len(file) * 8`. It also copies in github.com/bgentry/go-netrc with license attribution, as this repository hasn't been updated in 7 years.

At some point, we'll want to refactor our netrc handling completely, but this fixes the issue for now.

### CODE REVIEW

File: private/pkg/netrc/netrc_unix_test.go [hunk 1]
```diff
@@ -140,6 +143,54 @@ func TestPutMachines(t *testing.T) {
 	)
 }
 
+// https://github.com/bufbuild/buf/issues/611
+func TestPutLotsOfBigMachinesSingleLineFiles(t *testing.T) {
+	t.Parallel()
+	// TODO: at size 10, this test passes, at size 100, it fails
+	size := 100
+	password := strings.Repeat("abcdefghijklmnopqrstuvwxyz", size)
```
Comment (bufdev) [inline private/pkg/netrc/netrc_unix_test.go:151]: Note if you are debugging, you might want to decouple the number of machines from the size of the password to try to better isolate the problem.

**Review by amckinney — APPROVED** [review]
lgtm. It'd be sweet if the owner of this repository was willing to take this change (or something similar) into the open-source equivalent.

**Comment by johanbrandhorst** [comment]
Would be interesting to see if this turns into an issue in golang/go with some more investigation.

**Review by doriable — APPROVED** [review]
