### PR TITLE
Set top-level `LintConfig` and `BreakingConfig` and use for image inputs

### LINKED ISSUE #3080: buf 1.32.2 breaking doesn't respect v2 config file when using binpb input
### What's up?

Sorry for lack of test case, but this should be pretty easy to reproduce:

I was trying to set up a check using `buf breaking` like this:

```
buf breaking image1.bin --against image2.bin --config buf.yaml
```

The image files were not generated by buf, they were generated by `protoc -o`

I tried using buf 1.32.2 with a config like:

```
version: v2
breaking:
  use:
    - WIRE
```

This did the breaking check using the default `FILE` level, the `WIRE` level was not respected. I also tried adding `ignore` settings that were not respected.

I downgraded to buf 1.6.0 and used the same command line with the same config except `version: v1`, and it respected the breaking settings as expected.

### PR DESCRIPTION
**Pull request by doriable**
This PR exposes the top-level lint and breaking configs for `buf.yaml` files.

For `v1` `buf.yaml` files, there is only ever one `ModuleConfig`, so the
corresponding lint and breaking configs are used.

For `v2` `buf.yaml` files, if a top-level lint and/or breaking config exists, then
we return those.
Otherwise, `TopLevelLintConfig()`/`TopLevelBreakingConfig` will return `nil`.

We use the top-level lint/breaking configs, if possible, with image inputs, since we
cannot determine which specific `v2` module config to use with images. In
the case where there is no top-level config, we fall back to defaults.

Fixes #3080

### CODE REVIEW

**Comment by doriable** [comment]
I've also tested this against the user repro in the issue.

File: private/buf/bufctl/controller.go [hunk 1]
```diff
@@ -378,8 +378,8 @@ func (c *controller) GetTargetImageWithConfigs(
 		if err != nil {
 			return nil, err
 		}
-		lintConfig := bufconfig.DefaultLintConfigV1
-		breakingConfig := bufconfig.DefaultBreakingConfigV1
+		lintConfig := bufconfig.DefaultLintConfigV2
```
Comment (pkwarren) [inline private/buf/bufctl/controller.go:381]: We might want to leave this as V1 here for backwards compatibility (if no config file is found).

I also noticed that it appears that `DefaultLintConfigV2` isn't passing the right value for `allowCommentIgnores` - it should be `true` I think to match the new behavior when parsing from the external config file?

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 2]
```diff
@@ -275,6 +300,14 @@ func (c *bufYAMLFile) ModuleConfigs() []ModuleConfig {
 	return slicesext.Copy(c.moduleConfigs)
 }
 
+func (c *bufYAMLFile) DefaultLintConfig() LintConfig {
+	return c.defaultLintConfig
+}
+
+func (c *bufYAMLFile) DefaultBreakingConfig() BreakingConfig {
+	return c.defaultBreakingConfig
```
Comment (pkwarren) [inline private/bufpkg/bufconfig/buf_yaml_file.go:308]: If these are nil, shouldn't we return the default configs from moduleConfigs[0] as documented in the method docs? I don't think we want to return nil here ever.

File: private/bufpkg/bufconfig/lint_config.go [hunk 3]
```diff
@@ -34,7 +34,7 @@ var (
 		false,
 		false,
 		"",
-		false,
+		true, // We default to allowing comment ignores in v2
```
Comment (doriable) [inline private/bufpkg/bufconfig/lint_config.go:37]: @pkwarren caught an issue with the default `v2` lint config, which should default to allowing comment ignores (https://buf.build/docs/configuration/v2/buf-yaml)

>       # v1 configurations had an allow_comment_ignores option to opt-in to comment ignores.
>       #
>       # In v2, we allow comment ignores by default, and allow opt-out from comment ignores
>       # with the disallow_comment_ignores option.
>       disallow_comment_ignores: false

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 4]
```diff
@@ -74,6 +74,18 @@ type BufYAMLFile interface {
 	// All ModuleConfigs will have unique ModuleFullNames.
 	// Sorted by DirPath.
 	ModuleConfigs() []ModuleConfig
+	// DefaultLintConfig returns the DefaultLintConfig for the File.
+	//
+	// For v1 buf.yaml files, this will be the default v1 lint config.
```
Comment (pkwarren) [inline private/bufpkg/bufconfig/buf_yaml_file.go:79]: Why we wouldn't return the top-level config always for v1 buf.yaml files to match v2 behavior?

File: private/bufpkg/bufconfig/buf_yaml_file.go (hunk 2 above)
Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go:308]: Hmm, you're right -- yeah, if the constructor is used and `nil` is set, we don't want to return `nil`.

File: private/buf/bufctl/controller.go (hunk 1 above)
Comment (doriable) [reply private/buf/bufctl/controller.go:381]: Yeah, it's fair for back compat to set this back to `v1`. And yes, made an adjustment to `v2` defaults :)

File: private/bufpkg/bufconfig/buf_yaml_file.go (hunk 4 above)
Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go:79]: Hmm... yeah, I suppose that is correct -- since for `v1` `buf.yaml`'s, there really only is "one top-level" config, and if that isn't set, it just returns default v1, and we should stick to that. Going to adjust the docs and the code accordingly.

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 5]
```diff
@@ -76,13 +76,13 @@ type BufYAMLFile interface {
 	ModuleConfigs() []ModuleConfig
 	// DefaultLintConfig returns the DefaultLintConfig for the File.
 	//
-	// For v1 buf.yaml files, this will be the default v1 lint config.
+	// For v1 buf.yaml files, there is only ever a single ModuleConfig, so that is returned.
```
Comment (pkwarren) [inline private/bufpkg/bufconfig/buf_yaml_file.go:79]:
```suggestion
	// For v1 buf.yaml files, there is only ever a single ModuleConfig, so its LintConfig is returned.
```

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 6]
```diff
@@ -76,13 +76,13 @@ type BufYAMLFile interface {
...
 	// For v2 buf.yaml files, if a top-level lint config exists, then it will be the top-level
 	// lint config. Otherwise it is the default v2 lint config.
 	DefaultLintConfig() LintConfig
 	// DefaultBreakingConfig returns the DefaultBreakingConfig for the File.
 	//
-	// For v1 buf.yaml, this will be the default v1 breaking config.
+	// For v1 buf.yaml files, there is only ever a single ModuleConfig, so that is returned.
```
Comment (pkwarren) [inline private/bufpkg/bufconfig/buf_yaml_file.go:85]:
```suggestion
	// For v1 buf.yaml files, there is only ever a single ModuleConfig, so its BreakingConfig is returned.
```

**Review by pkwarren — APPROVED** [review]

**Review by oliversun9 — APPROVED** [review]

**Review by pkwarren — APPROVED** [review]

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 7]
```diff
@@ -275,6 +300,20 @@ func (c *bufYAMLFile) ModuleConfigs() []ModuleConfig {
...
+func (c *bufYAMLFile) DefaultLintConfig() LintConfig {
+	if c.defaultLintConfig == nil {
+		return c.moduleConfigs[0].LintConfig()
+	}
+	return c.defaultLintConfig
+}
+
+func (c *bufYAMLFile) DefaultBreakingConfig() BreakingConfig {
+	if c.defaultBreakingConfig == nil {
+		return c.moduleConfigs[0].BreakingConfig()
```
Comment (bufdev) [inline private/bufpkg/bufconfig/buf_yaml_file.go:312]: This isn't actually correct - this is just choosing a single configuration among potentially many and calling it the default, which is what we've tried to avoid pretty consistently with v2. I think what you're actually looking for in this PR is some concept of "if there is a single configuration, give it to me, otherwise tell me it is not present". What this logic looks like:

```func
SingleLintConfig() (LintConfig, bool)
```

- If v1, return the v1 configuration.
- If v2:
  - If there is one module with attached configuration, return the attached configuration. Else, return the top-level configuation.
  - If there is more than one module, return false

If you get false, do nothing, as we do right now.

Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go:312]: So if a user passes the following file to `--config`:

```
version: v2
lint:
  use:
    - WIRE
breaking:
  use:
    - FILE
modules:
  - path: foo
  - path: bar
    lint:
      use:
        - DEFAULT
      except:
        - IMPORT_USED
  - path: vendor
```

Wouldn't we want them to pick up the top-level configs for the default?

Comment (bufdev) [reply private/bufpkg/bufconfig/buf_yaml_file.go:312]: We'd probably want to error, or at least print a warning along the lines of:

```
WARN Configuration {from flag,at $PATH was used} but this configuration had multiple modules. Buf cannot deduce which {lint,breaking} configuration to use with your image. Ignoring your configuration and using the default configuration instead.
```

I could see an argument to also modify the logic to "if >1 modules, return the top-level module", but that may just leave us open to even more support stuff in the long-term.

Going a different direction, we could take the position that for image inputs only, we always take the top-level configuration, and never look into specific module configs. This would mean that if you had the following:

```
version: v2
modules:
  - path: .
     lint: ...
```

The `modules[0].LintConfig` would not be picked up and propagated. The position here would be that module-specific configuration never applies to an image, and we treat configuration for an image as if it were a "new" module in the `modules` list.

This may be what `moduleConfigs[0]` does in practice for v1, but not for v2, but I'd also be comfortable with adopting this position, it seems intellectually consistent.

Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go:312]: I am a fan of the latter approach for images. For `v1`, the behaviour will stay the same since there should only ever be a single lint/breaking config. For `v2`,  we check for a top-level config, and if nothing is there, then we would use whatever the version defaults are. And yes, in the case you provided, where there is a single module, `path: .`, that would not be considered the default configuration. Changes incoming.

File: private/bufpkg/bufconfig/buf_yaml_file.go [hunk 8]
```diff
@@ -74,6 +74,13 @@ type BufYAMLFile interface {
 	// All ModuleConfigs will have unique ModuleFullNames.
 	// Sorted by DirPath.
 	ModuleConfigs() []ModuleConfig
+	// TopLevelModuleConfig returns the top-level ModuleConfig for the File.
+	//
+	// For v1 buf.yaml files, there is only ever a single ModuleConfig, so this is returned.
+	// For v2 buf.yaml files, if a top-level module config exists, then it will be the top-level
+	// module config. Otherwise, this will return nil, so callers should be aware this may be
+	// empty.
+	TopLevelModuleConfig() ModuleConfig
```
Comment (bufdev) [inline private/bufpkg/bufconfig/buf_yaml_file.go:83]: Why is this a `ModuleConfig`? We only want `LintConfig` and `BreakingConfig`, I don't know what a top-level `ModuleConfig` is in terms of v2

File: private/buf/bufctl/controller.go [hunk 9]
```diff
@@ -393,20 +394,49 @@ func (c *controller) GetTargetImageWithConfigs(
...
-				// breaking config to apply.
-			default:
-				return nil, syserror.Newf("unknown FileVersion: %v", fileVersion)
+			} else {
+				// Otherwise we use the file path
+				configInfo = bufYAMLFile.ObjectData().Name()
+			}
+			if topLevelModuleConfig := bufYAMLFile.TopLevelModuleConfig(); topLevelModuleConfig != nil {
+				if bufYAMLFile.FileVersion() == bufconfig.FileVersionV2 && len(bufYAMLFile.ModuleConfigs()) > 1 {
+					c.logger.Sugar().Warnf(
```
Comment (bufdev) [inline private/buf/bufctl/controller.go:422]: I don't think we need to print either of these warnings, I just think we take the position that doing lint or breaking change detection for an image means we treat it like any other module - if it doesn't have a configuration, we use the top-level configuration, which may be empty and then we just go to default.

File: private/bufpkg/bufconfig/buf_yaml_file.go (hunk 8 above)
Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go:83]: I used `ModuleConfig` because it worked better for the warnings and also to account for situations like:

```
version: v2
name: <remote>/<owner>/<module>
```

But in that case, it would be the default anyway, so it doesn't super matter, and also since we're not printing out the warnings, I can swap it back to `LintConfig` and `BreakingConfig`.

Comment (doriable) [reply private/bufpkg/bufconfig/buf_yaml_file.go]: Updated back to `LintConfig` and `BreakingConfig`, and updated the PR title + description.

**Review by bufdev — APPROVED** [review]
